# Generated by Django 5.1.3 on 2026-01-11 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("general", "General Cleaning"),
                            ("deep", "Deep Cleaning"),
                            ("endOfLease", "End of Lease"),
                            ("moveIn", "Move-in Cleaning"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("once", "Just Once"),
                            ("weekly", "Weekly"),
                            ("fortnightly", "Fortnightly"),
                            ("monthly", "Monthly"),
                        ],
                        default="once",
                        max_length=20,
                    ),
                ),
                ("bedrooms", models.IntegerField(default=1)),
                ("bathrooms", models.IntegerField(default=1)),
                ("kitchen", models.IntegerField(default=1)),
                ("living_dining", models.IntegerField(default=1)),
                ("laundry", models.IntegerField(default=0)),
                ("storey", models.IntegerField(default=1)),
                ("selected_add_ons", models.JSONField(blank=True, default=dict)),
                ("add_on_details", models.JSONField(blank=True, default=dict)),
                ("selected_date", models.DateField()),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(max_length=20)),
                ("sms_reminders", models.BooleanField(default=True)),
                ("unit_number", models.CharField(blank=True, max_length=50)),
                ("street", models.CharField(max_length=200)),
                ("suburb", models.CharField(max_length=100)),
                ("postcode", models.CharField(max_length=10)),
                (
                    "has_pet",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=10,
                    ),
                ),
                (
                    "hear_about_us",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("google", "Google Search"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("friend", "Friend/Family Referral"),
                            ("flyer", "Flyer"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("special_notes", models.TextField(blank=True)),
                (
                    "cleanliness_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "1 - Very Clean"),
                            ("2", "2 - Moderately Clean"),
                            ("3", "3 - Needs Cleaning"),
                            ("4", "4 - Heavily Soiled"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "parking",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("driveway", "Driveway"),
                            ("street", "Street Parking"),
                            ("garage", "Garage"),
                            ("visitor", "Visitor Parking"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "flexible_date_time",
                    models.CharField(
                        blank=True,
                        choices=[("yes", "Yes"), ("no", "No")],
                        max_length=10,
                    ),
                ),
                (
                    "access",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("home", "I will be home"),
                            ("key", "Leave a key"),
                            ("lockbox", "Lockbox"),
                            ("doorcode", "Door code"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("price_details", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "ordering": ["-created_at"],
            },
        ),
    ]
