# Generated by Django 5.1.3 on 2026-01-13 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="add_on_details",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="price_details",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="booking",
            name="selected_add_ons",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
