# Generated by Django 6.0.1 on 2026-03-26 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leads", "0002_alter_booking_add_on_details_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="selected_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
