# Generated by Django 5.1.3 on 2026-01-11 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=200, unique=True)),
                (
                    "excerpt",
                    models.TextField(
                        help_text="Short description for preview (max 300 characters)",
                        max_length=300,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Full blog post content (supports HTML)"
                    ),
                ),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="blog/images/"),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="SEO meta description (max 160 characters)",
                        max_length=160,
                    ),
                ),
                (
                    "meta_keywords",
                    models.CharField(
                        blank=True, help_text="Comma-separated keywords", max_length=200
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="e.g., Cleaning Tips, Eco-Friendly, Home Care",
                        max_length=100,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("published_date", models.DateTimeField(blank=True, null=True)),
                ("views", models.IntegerField(default=0)),
                (
                    "featured",
                    models.BooleanField(default=False, help_text="Show on homepage"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="blog_posts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-published_date", "-created_at"],
            },
        ),
    ]
